# name: Build and Push Docker Images

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build_and_push:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Configure AWS credentials
#       uses: aws-actions/configure-aws-credentials@v2
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: us-east-1  

#     - name: Login to Amazon ECR
#       id: login-ecr
#       uses: aws-actions/amazon-ecr-login@v1

#     - name: Build, tag, and push book-service image
#       run: |
#         IMAGE_TAG=${{ github.sha }}
#         IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/book-service:${IMAGE_TAG}"
#         docker build -t $IMAGE_URI ./book-service
#         docker push $IMAGE_URI

#     - name: Build, tag, and push library-service image
#       run: |
#         IMAGE_TAG=${{ github.sha }}
#         IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/library-service:${IMAGE_TAG}"
#         docker build -t $IMAGE_URI ./library-service
#         docker push $IMAGE_URI
