name: Deploy to Docker Swarm with Environment File

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      book_service_tag:
        description: 'Tag for the book-service image'
        required: true
        default: b851abeee82a48d2502eaa1e51aa95e2b5db6e25
      env_file_name:
        description: 'Name of the environment file on the Swarm manager'
        required: true
        default: .env

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add SSH known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SWARM_MANAGER_IP1 }} >> ~/.ssh/known_hosts
        ssh-keyscan -H ${{ secrets.SWARM_MANAGER_IP2 }} >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts

    - name: Create environment file on Swarm manager
      env:
        SWARM_MANAGER_IP1: ${{ secrets.SWARM_MANAGER_IP1 }}
        ENV_FILE_CONTENTS: ${{ secrets.ENV_FILE_CONTENTS }}
        ENV_FILE_NAME: ${{ github.event.inputs.env_file_name }}
      run: |
        echo "$ENV_FILE_CONTENTS" | ssh ubuntu@$SWARM_MANAGER_IP1 "cat > ~/$ENV_FILE_NAME"
        echo "Environment file '$ENV_FILE_NAME' created on Swarm manager"

    - name: Generate docker-compose.yml with specified tags
      run: |
        cat > docker-compose.yml << EOF
        version: '3.8'

        services:
          book-service:
            image: 023704516495.dkr.ecr.us-east-1.amazonaws.com/book-service:${{ github.event.inputs.book_service_tag }}
            deploy:
              replicas: 2
            ports:
              - "8080:8080"
            env_file:
              - ./${{ github.event.inputs.env_file_name }}
        EOF

        cat docker-compose.yml

    - name: Deploy stack to Docker Swarm manager
      env:
        SWARM_MANAGER_IP1: ${{ secrets.SWARM_MANAGER_IP1 }}
        ENV_FILE_NAME: ${{ github.event.inputs.env_file_name }}
      run: |
        scp docker-compose.yml ubuntu@$SWARM_MANAGER_IP1:~/docker-compose.yml
        ssh ubuntu@$SWARM_MANAGER_IP1 "docker stack deploy --compose-file ~/docker-compose.yml --env-file ~/$ENV_FILE_NAME my-microservices-stack"
        echo "Deployment completed successfully"